export const theme = {
    primaryColor: '#6A4BFF',
    secondaryColor: '#007bff',
    notificationError: '#FA3B33',
    backgroundColor: '#ffffff',
    backgroundColorActive: '#DDEDFF',
    textColor: '#ffffff',
    accentColor: '#ffc107',
    borderColor: '#B6B6B6',
    h1: '26px',
    h2: '22px',
    h3: '20px',
    h4: '18px',
    h5: '16px',
    h6: '14px',
    fontFamily: "'Roboto', sans-serif",
    fontSize: '16px',
    lineHeight: '1.5',
    headingFont: "'Montserrat', sans-serif",
    bodyFont: "'Open Sans', sans-serif",
    spacingSmall: '8px',
    spacingMedium: '16px',
    spacingLarge: '24px',
    buttonPadding: '10px 20px',
    containerWidth: '1200px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
    borderRadius: '4px',
    borderWidth: '1px',
    transitionDuration: '0.3s',
    easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
    easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
    zIndexDropdown: '100',
    zIndexModal: '200',
    zIndexTooltip: '300',
    lightThemeBackground: '#fff',
    darkThemeBackground: '#121212',
    linkColor: '#007bff',
    linkHoverColor: '#0056b3',
    focusOutlineColor: 'rgba(0, 123, 255, 0.6)',
    breakpointMobile: '480px',
    breakpointTablet: '768px',
    breakpointDesktop: '1200px',
}